services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
            - ./storage:/var/www/html/storage
            - ./public:/var/www/html/public
        container_name: my_laravel_app
        expose:
            - 9000
        depends_on:
            - mysql

    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www
            - ./.docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        depends_on:
            - app
        container_name: project_nginx

    mysql:
        image: mysql:8.2
        restart: always
        environment:
            MYSQL_DATABASE: uaitlab
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-ssl
        container_name: project_db

    meilisearch:
        image: getmeili/meilisearch:latest
        container_name: meilisearch
        ports:
            - "7700:7700"
        volumes:
            - meilisearch_data:/meili_data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - es_data:/usr/share/elasticsearch/data
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:8.2.3
        environment:
            - ELASTICSEARCH_HOST=elasticsearch:9200
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        volumes:
            - es_data:/usr/share/elasticsearch/data

volumes:
    meilisearch_data:
    es_data:
        driver: local
