services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        container_name: my_laravel_app
        expose:
            - 9000
        depends_on:
            - mysql

    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www
            - ./.docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        depends_on:
            - app
        container_name: project_nginx

    mysql:
        image: mysql:8.2
        restart: always
        environment:
            MYSQL_DATABASE: uaitlab
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-ssl
        container_name: project_db

    meilisearch:
        image: getmeili/meilisearch:v0.28
        ports:
            - "7700:7700"
        volumes:
            - meilisearch_data:/meili_data

volumes:
    meilisearch_data:
